### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jw2554** [zeitlings/alfred-set-default-browser#2]
Thanks for writing the only Alfred 5 workflow for resetting default browser. I am unable to make it work. I type in the command sdb and see many browser icons in the drop down menu. But when I hit enter on Chrome, for example, nothing happens. I did read through your "file action" explanation regarding the bundle identifier information. I do not understand it. At the moment, there is one type listed under "types:" com.apple.application-bundle. Can you help?
<img width="1165" alt="Screenshot 2023-04-18 at 9 19 26 AM" src="https://user-images.githubusercontent.com/64379077/232790008-cf21bb15-a5d9-4091-a5bf-6d8ff11ca8e7.png">

**Comment by zeitlings** [comment]
Hey @jw2554, is _nothing_ happening or is there perhaps a notification? If you open the debug window in Alfred (<kbd>⌘</kbd><kbd>D</kbd>) and try to switch to chrome, is there a message about the error?

The File Action can give you information about the bundle identifier of an app, which you can then copy-paste to create a new option in the "List Filter" object, i.e. a new browser to select when you type `sdb`. However, Chrome is already in the list and should work (unless the identifier changed since last time I checked). 

The reason there is only one type for the File Action object, namely `com.apple.application-bundle`, is to ensure that only apps can be presented to it. For example, if you type "Chrome" in Alfred and then hit the right arrow key on the Chrome app, you can pass it to the `Bundle Identifier Information` File Action to get its bundle id. You really only need this if you're using a browser that's not in the list. But it won't hurt to verify that the identifier is correct.

If it continues to not work, I'd suggest you first see if there is any debugging information available, and if there is, to post it here.

![out2](https://user-images.githubusercontent.com/25689591/232851303-e84c33e2-5e61-4311-86c6-4c8c1d13bd54.gif)

**Comment by jw2554** [comment]
Hi Patrick, thanks so much for your reply. Here’s the debug info:

[10:13:11.646] Logging Started...
[10:13:36.045] Default Browser[List Filter] Processing complete
[10:13:36.046] Default Browser[List Filter] Passing output 'com.apple.Safari' to Run Script
[10:13:36.063] ERROR: Default Browser[Run Script] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[10:13:36.066] Default Browser[Run Script] Processing complete
[10:13:36.067] Default Browser[Run Script] Passing output '' to Split Arg
[10:13:36.067] Default Browser[Split Arg] Processing complete
[10:13:36.068] Default Browser[Split Arg] Passing output '' to Conditional
[10:13:36.068] Default Browser[Conditional] Processing complete
[10:13:36.069] Default Browser[Conditional] Passing output '' to Debug
[10:13:36.069] Default Browser[Debug] ''
[10:13:36.070] Default Browser[Debug] Processing complete
[10:13:36.073] Default Browser[Debug] Passing output '' to Post Notification

I don’t know what I’m reading. Can you help?
- Jie

**Comment by zeitlings** [comment]
Did the previous version of the workflow work for you? It looks like the problem might be with the Xcode CLI tools. You can try resetting the path, or perhaps install the tools from the terminal in the first place: 

```shell
xcode-select --install
sudo xcode-select -s /Library/Developer/CommandLineTools/
```

**Comment by jw2554** [comment]
Hi Patrick, thanks for your note. I’d love to understand what you think might help me fix the problem. I don’t know much about how the terminal, neither do I have training in coding or computer science. But I’m very good at following instructions. Do you think you can instruct me how to use the terminal for the Xcode?
- Jie

**Comment by zeitlings** [comment]
Hey, Jie. We can try! It should be as simple as 
- opening the Terminal App
- pasting the first command `xcode-select --install` and hitting enter (will install the tools if not present)
    - At this point you can already check if the workflow works. In that case you can skip the rest and relax.
- pasting the second command `sudo xcode-select -s /Library/Developer/CommandLineTools/` and hitting enter
    - since this command is prefixed with `sudo` (=super-user-do), you will be asked to enter the login password for your mac. You won't see that anything has been typed, but your input will be registered.


<img width="612" alt="Screenshot1" src="https://github.com/zeitlings/alfred-set-default-browser/assets/25689591/27c752ab-7d0b-4dd2-931c-ef8febcbd748">

<img width="706" alt="Screenshot2" src="https://github.com/zeitlings/alfred-set-default-browser/assets/25689591/bb8d5eb3-0fe2-4347-af6f-58c94bf87867">

<img width="706" alt="Screenshot3" src="https://github.com/zeitlings/alfred-set-default-browser/assets/25689591/58a4eee9-6ff4-46ee-996e-b02c89c27c54">

Your Terminal will look differently
